// programs actions
export const FETCH_PROGRAMS_REQUEST = 'FETCH_PROGRAMS_REQUEST'
export const FETCH_PROGRAMS_SUCCESS = 'FETCH_PROGRAMS_SUCCESS'
export const FETCH_PROGRAMS_ERROR = 'FETCH_PROGRAMS_ERROR'

// partners actions
export const FETCH_PARTNERS_REQUEST = 'FETCH_PARTNERS_REQUEST'
export const FETCH_PARTNERS_SUCCESS = 'FETCH_PARTNERS_SUCCESS'
export const FETCH_PARTNERS_ERROR = 'FETCH_PARTNERS_ERROR'

export const FETCH_PARTNERS_MAJOR_REQUEST = 'FETCH_PARTNERS_MAJOR_REQUEST'
export const FETCH_PARTNERS_MAJOR_SUCCESS = 'FETCH_PARTNERS_MAJOR_SUCCESS'
export const FETCH_PARTNERS_MAJOR_ERROR = 'FETCH_PARTNERS_MAJOR_ERROR'

// testimonials actions
export const FETCH_TESTIMONIALS_REQUEST = 'FETCH_TESTIMONIALS_REQUEST'
export const FETCH_TESTIMONIALS_SUCCESS = 'FETCH_TESTIMONIALS_SUCCESS'
export const FETCH_TESTIMONIALS_ERROR = 'FETCH_TESTIMONIALS_ERROR'
